version: '3.8'

services:

  goodboys-db:
    container_name: goodboys-db
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "goodboys", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 50
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goodboys

  goodboys-app:
    container_name: goodboys-app
    image: imvad/telegram-bot-search-goodboy:2.5.1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      - goodboys-db
    environment:
      APPLICATION_PORT: 8040
      TOKEN:
      DATABASE_HOST: goodboys-db
      DATABASE_PORT: 5432