server:
  port: ${APPLICATION_PORT:8040}
spring:
  application:
    name: telegram-bot-search-goodboy
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:8041}/${DATABASE_NAME:goodboys}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  config:
    import: messages.yaml

logging:
  level:
    bot: ${LOGGING_LEVEL_APP:debug}
    org.springframework: ${LOGGING_LEVEL_SPRING:info}
    com.zaxxer.hikari.pool: error

telegram:
  token: ${TOKEN}
  username: ${BOT_USERNAME:@vmPidarBot}
  admin-id: 186736203