server:
  port: ${APPLICATION_PORT:8040}
spring:
  application:
    name: telegram-bot-search-goodboy
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:8041}/${DATABASE_NAME:goodboys}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

logging:
  level:
    bot: ${LOGGING_LEVEL_APP:debug}
    org.springframework: ${LOGGING_LEVEL_SPRING:info}

telegram:
  token: ${TOKEN}
messages:
  rooster:
    - ezB9LCDQv9C10L/QtSDQsdC70Y/RgtGMLCDQuNC00Lgg0YXQsNCy0L7RgdGC0Ywg0YHQstC+0ZEg0ZHQsdGD0YfQuNC1INC/0Y7RgNC1
    - ezB9IC0g0YXRg9GR0LvQvtC80LDRgtGL0Lk=
    - ezB9LCDQv9C+0YXQvtC20LUg0YLQtdCx0LUg0YHQtdCz0L7QtNC90Y8g0LrQvtCy0YvRgNC90YPQu9C4INGB0LrQvtGA0LvRg9C/0LrRgw==
    - 0LHQu9C10YHQuiDQsiDQvtGH0L7Rh9Cw0YUg0YMgezB9
    - ezB9LCDRh9GC0L4g0YEg0LXQsdCw0LvQvtC8Pw==
    - ezB9LCDQsCDRgyDRgtC10LHRjyDRjyDRgdC80L7RgtGA0Y4g0LTRi9C80L7RhdC+0LQg0L/QvtGH0LjRidC1INC+0YHRgtCw0LvRjNC90YvRhSDRgdC10LPQvtC00L3Rjw==
    - 0JrQvtC20LDQvdC90LDRjyDQv9GD0LvRjyDQsiDQutC+0LbQsNC90L7QvCDRgdGC0LLQvtC70LUg0YMgezB9
    - 0JDRgNGF0LjQv9C40LTQvtGAIHswfQ==
    - 0JLQvtC90LfQsNC10YLRgdGPINC/0LvRg9Cz0L7QvCDQsiDRgtGD0LPQvtC5INGH0LXRgNC90L7Qt9GR0LwgezB9
    - 0JHQq9Ch0KLQoNCr0JUg0JLQq9Cf0JvQkNCi0KssINCd0JDQlNCB0JbQndCr0Jkg0JHQo9Ca0JzQldCZ0JrQq9CgIC0gezB9
    - 0L/RgNC+0LHQuNGC0LDRjyDRgdGA0LDRh9C10LvQu9CeINGDIC0gezB9
    - 0YjQtdCx0YPRgNGC0ZbQvdC90Y8g0LIg0LTRg9C/0LvRliDRgyB7MH0=
    - ezB9INGI0LXRgNGI0LDQstGL0Lkg0LLQsNGA0LXQvdC40Lo=
    - ezB9INC30LDRgdC80LDQu9C10L3QvdCw0Y8g0YHQvtGB0YvRgdC60LA=
    - ezB9LCDQotCrINCn0J4g0JTQq9Cg0K/QktCr0Jk=
    - ezB9LCDQv9C+0LzQvdC4LCDRgtC10LHQtSDRgtGD0YIg0L3QtSDRgNCw0LTRiw==
    - ezB9INC70Y7QsdC40YLQtdC70Ywg0YHQtNC10LvQsNGC0Ywg0LzRj9GB0L3QvtC5INGD0LrQvtC7
    - 0J/QtdGA0LTRkdGIINGF0YPRj9C80Lgg0L/QsNGF0L3QtdGCINGB0LXQs9C+0LTQvdGPINGC0L7Qu9GM0LrQviDRgyB7MH0=
    - ezB9INCi0Ksg0KnQniwg0JPQldCZLdCc0J7QodCa0JDQm9CsPw==
    - ezB9INGB0LrQsNC20Lgg0YLRgNC40YHRgtCw
    - ezB9INCz0L7RgtC+0LLRjCDQutC+0L/RgtC40LvRjNC90YMsINCx0YPQtNC10Lwg0LPQvtGC0L7QstC40YLRjCDQsiDQvdC10Lkg0YHQstC+0Lgg0YHQvtGB0LjRgdC+0L3Riy4gbG9ocGlkb3I=
    - ezB9INC30LDQtNC+0Log0YLQviDRgyDRgtC10LHRjyDRgdC10LPQvtC00L3RjyDQv9C+0YHQu9Cw0LHQtdC1INC+0YHRgtCw0LvRjNC90YvRhQ==
    - ezB9INCw0YUg0YLRiyDQttC+0LLQsNC90L3QsNGPINC20L7Qv9Cw
  already_started:
    - 0J3RgyDRkdCx0LDQvdGL0Lkg0YLRiyDQutCw0LfQuNC90LDQuiDRgdGD0LrQsCwg0LfQsNC/0YPRgdC60LDQu9C4INGD0LbQtSwg0L3Rgy4uLiDQodC10LPQvtC00L3RjyDQtNGL0YDRj9Cy0YvQuSB7MH0=
    - 0J/QvtCx0LDRiNC60LUg0YHQtdCx0LUg0L/QvtGC0YvQutCw0Lkg0YHQv9C10YDQvNC+0LHQsNC6LCDQuCDQs9C70LDQt9CwINC/0YDQvtGC0YDQuCwg0L/QuNC00L7RgCB7MH0g0YPQttC1INCy0YvRj9Cy0LvQtdC9
  stats:
    - 0JTQtdCy0LDRh9C60LgsINC/0YDQuNCz0L7RgtC+0LLRjNGC0LUg0YHQstC+0Lgg0LPRgNGP0LfQvdGL0LUg0YHRgNCw0LvRjNC90LjQutC4INC6INGA0LDQt9Cx0L7RgNGDINC/0L7Qu9C10YLQvtCyOg==
    - 0JfQsNCz0L7QvdGP0LXQvCDQstGB0LXRhSDQv9C40LTQsNGA0L7QsiDQsiDQstC+0LvRjNC10YA6
    - 0JLRgdC1INC/0LjQtNC+0YDRiyDQsiDQvtC00L3QvtC8INGB0L7QvtCx0YnQtdC90LjQuDo=
    - 0K8g0YHQvtCx0YDQsNC7INCy0YHQtdGFINC30LDQtNC90LXQv9GA0LjQstC+0LTQvdGL0YU6
    - 0JfRltCx0YDQsNC90L3RjyDRgyDRhtC10YDQutCy0ZYg0KHQstGP0YLQvtCz0L4g0J/RltC00L7RgNCwINC/0L7Rh9C40L3QsNGU0YLRjNGB0Y86
    - 0JPQvtC70YPQsdC60LgsINGD0LLQsNCz0LAhINCj0YUsINGP0Log0LLQsNGBINCx0LDQs9Cw0YLQvjo=
    - 0JrRgtC+INGG0Y0g0YLRg9GCINGB0LDQvNGL0Lkg0LLQvtC30LHRg9C20LTQtdC90L3Ri9C5Pw==
    - 0JPQu9Cw0LLQvdGL0Lkg0LDRgNGF0LjQv9C40LTQvtGAINGC0L7Qu9GM0LrQviDQvtC00LjQvSB7MH0sINCwINCy0YHQtSDQvtGB0YLQsNC70YzQvdGL0LUg0LvQuNGI0Ywg0LXQs9C+INC/0L7QtNGB0L7RgdGLLg==
    - 0J/QvtC/0L/QtdC90LPQsNCz0LXQvSDQvtGC0LrRgNGL0YIg0YMg0YHQu9C10LTRg9GO0YnQuNGFINC/0YPQv9GB0LjQutC+0LI6
    - 0JvRg9C/0Y/RgtGB0Y8g0LIg0YLRg9C30LAsINC90L4g0L3QtSDQuNCz0YDQsNGO0YIg0LIg0LrQsNGA0YLRizo=
    - 0KLQtdGA0L/QuCDQv2nQtNGA0Y7Quiwg0L9p0LTQsNGA0LDRgdC+0Lwg0YHRgtCw0L3QtdGIOg==
  no_active_players:
    - 0J/Rg9C6INGB0YDQtdC90YzQui4uLiDQkCDRgyDQstCw0YEg0YLRg9GCINC90LXRgiDQsNC60YLQuNCy0L3Ri9GFINC40LPRgNC+0LrQvtCyLiDQn9GA0L7RgtGL0LrQsNC50YLQtSAvcmVnINCwINC/0L7RgtC+0Lwg0L/QvtCz0L7QstC+0YDQuNC8Lg==
  registration:
    - CAACAgIAAxkBAAEHfQxj1UsbUi3saisrTmv6LdzKnbvIpgACxw0AAoLZUUqPZ3pCY5lGPC0E
    - CAACAgIAAxkBAAEHcyNj0jQ0oF0zeAyjL-bpil_2t8yckgACDxEAAojF0Usu_WLHr8Vjzi0E
    - CAACAgIAAxkBAAEHfQ5j1Ut46om2fn__bpmMtjhTrZKxzgACzBQAAgrXyUsa7GgoHs1N_y0E
    - CAACAgIAAxkBAAEHfRBj1UuTLxYbh7UEUHAz2w8M05-uBwACkhAAAqtKyUuSgBNYR-8rQC0E
    - CAACAgIAAxkBAAEHfRJj1UuioXwrr_fo4egB6kQ1x7IB1gACChAAAuYj0UgrWuoknRbbxi0E
    - CAACAgIAAxkBAAEHfSlj1U5nmjdVAAHV5xX3x9ocfGc9Fo4AAkwBAAJLXiELexcuHq07_kotBA
  user_already_playing:
    - 0KLRiyDRh9C1LCDQtNGD0YDQsNC6INGH0YLQviDQu9C4PyDQotGLINGD0LbQtSDQt9Cw0YDQtdCz0LDQvSDQsdGL0LssINC00L7Qu9Cx0LDRkdCx0LjQvdCw
