spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    url: jdbc:h2:file:./h2/goodboys;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    password: ''
server:
  port: ${APPLICATION_PORT:8040}
telegram:
  token: ${TOKEN}
